/* Generated by gbrecomp */
#ifndef Crystal_Clear_H
#define Crystal_Clear_H

#include "gbrt.h"

const GBConfig* Crystal_Clear_default_config(void);
void Crystal_Clear_run(GBContext* ctx);
void Crystal_Clear_init(GBContext* ctx);
int Crystal_Clear_main(int argc, char* argv[]);

#endif
